---
title: "Module 3"
author: "David Washburn"
date: "10/6/2019"
output: html_document
---

```Chapter 10```

```{r}

library(tidyverse)

as_tibble(iris) #Basically a data frame

tibble(x = 1:5, y = 1, z = x^2 + y) #Creating a tibble

#Creating another tibble

tb <- tibble(
  `:)` = "smile",
  ` ` = "space",
  `20001` = "number"
)

tb

#Creating a Tribble

tribble(
  ~x, ~y, ~z,
#--/---/-----
"a", 2, 3.6,
"b", 1, 8.5
)

#Testing out Printing

tibble(
  a = lubridate::now() + runif(1e3) * 86400,
  b = lubridate::today() + runif(1e3) * 30,
  c = 1:1e3,
  d = runif(1e3),
  e = sample(letters, 1e3, replace = TRUE)
)

library(nycflights13)

nycflights13::flights %>%
  print(n = 1, width = 2)

#Subsetting

df <- tibble(
  x = runif(5),
  y = rnorm(5)
)

df$x

df %>% .$x
```

```Chapter 11```

```{r}

#read_csv

read_csv("a,b,c,d
1,2,3,4
4,5,6,7")

read_csv("1,2,3\n4,5,6", col_names = FALSE)

read_csv("a,b,c\n1,2,.", na = ".")

#parse

x <- parse_integer(c("123", "345", "abc", "123.45"))
x

#factors

fruit <- c("apple", "banana")
parse_factor(c("apple", "banana", "bananana"), levels = fruit)
```

```chapter 12 ```

```{r}

#Making Data tidy is basically taking data and 'rearranging' it to be easier to use

library(tidyverse)

#gather() and spread() are really important

table4a  %>%
  gather(`1999`, `2000`, key = "year", value = "cases")

tidy4a <- table4a %>% 
  gather(`1999`, `2000`, key = "year", value = "cases")
tidy4b <- table4b %>% 
  gather(`1999`, `2000`, key = "year", value = "population")
left_join(tidy4a, tidy4b)

table2 %>%
  spread(key = type, value = count)
```

